# Generated by Django 6.0.6 on 2026-06-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vecinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bache', 'Bache'), ('basura', 'Basura acumulada'), ('alumbrado', 'Alumbrado dañado'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('numero_seguimiento', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('reportado', 'Reportado'), ('validado', 'Validado por junta'), ('derivado', 'Derivado al municipio'), ('proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='reportado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vecinos.vecino')),
            ],
            options={
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.reporte')),
            ],
            options={
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
